### PR TITLE
Futures 03

### PR DESCRIPTION
**Pull request by yoshuawuyts**
## Description
Migrate to the `std::Futures` API. Based on the excellent work in #10.

## Motivation and Context
This allows this crate to work with async/await.

Not everything from the `ext` trait works yet tho, but that shouldn't be a blocker to starting the migration.

## How Has This Been Tested?
Migrated all tests, and they pass!

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/rust-net-web/tide/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mmastrac** [comment]
Need help on this PR? Happy to pitch in and either work on cleanup/review (if @alexcrichton doesn't have bandwidth).

**Comment by yoshuawuyts** [comment]
@mmastrac sure, can always use an extra pair of eyes (:

**Comment by mmastrac** [comment]
@yoshuawuyts I've got the `ext` package compiling again and worked on some cleanups in this commit here: https://github.com/rustasync/futures-timer/pull/16/commits/998b3add7fae29c28d6a4b52510eae7299f78231

**Comment by mmastrac** [comment]
@alexcrichton Is adding the deps for `pin_utils` and `runtime` OK in this patch? I think we are pretty close to the end stage for getting this in.

**Comment by yoshuawuyts** [comment]
@mmastrac Alex currently doesn't have the bandwidth to maintain this package, so we've taken over maintenance with the working group. `pin-utils` is a very small package, and `runtime` is a development dependency only -- it should be no problem (:

**Comment by yoshuawuyts** [comment]
This has been open for a while, and there seem to be no outstanding concerns. Going to go ahead and merge this patch!

**Comment by mmastrac** [comment]
Thanks for all the work on this @yoshuawuyts! I moved my last bit of work into pr #17.

**Pull request merged**
