### PR TITLE
get ext working + cleanup

### PR DESCRIPTION
**Pull request by mmastrac**
This is a cleanup patch - basically gets ext working again, runs `rustfmt` and gets the raw waker stuff ready to transition to `ArcWaker`.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@mmastrac this is looking really good! -- perhaps a nice addition would be a few small tests for the ext functionality so we can check that they work as intended.

**Comment by mattfs** [comment]
Thanks! I'll whip some of those up shortly and post in a follow-up PR.

**Comment by mmastrac** [comment]
Thanks! I'll whip those up shortly and post a new PR (re-posting comment from my non-work account :))

**Comment by mattfs** [comment]
@yoshuawuyts Do you mind merging this PR? I don't have write access.

**Pull request merged**
